[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
profile = "black"
py_version = 38
use_parentheses = true

[tool.poetry]
name = "nfcli"
version = "0.1.0"
description = "Nebulous: Fleet CLI. View fleet files and convert them into images."
authors = ["Jaghaimo <1764586+jaghaimo@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
xmltodict = "^0.13.0"
rich = "^12.4.4"
"discord.py" = "^1.7.3"
python-dotenv = "^0.20.0"
CairoSVG = "^2.5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
